<Project Sdk="Dalamud.NET.Sdk/14.0.1">
  <PropertyGroup>
    <AssemblyName>Kaleidoscope</AssemblyName>
    <Authors>MTVirux</Authors>
    <Description>Multi-character game data tracker and visualizer for FFXIV</Description>
    <Version>1.0.0.5</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Kaleidoscope.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OtterGui\OtterGui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.0" />
    <Reference Include="Dalamud.Bindings.ImGui" Private="false" />
  </ItemGroup>

</Project>
